language: scala
scala:
  - 2.11.12
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean scalastyle test

notifications:
  email:
    - lorenz.verzosa@databricks.com

